repos:
-   repo: local
    hooks:
    -   id: enforce-changelog
        name: Enforce changelog changes
        entry: bash -c "git diff --exit-code CHANGELOG.md"
        language: system
        verbose: false
