# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: compile_all_docx
        name: Compile DocX
        entry: bash -c 'pandoc docs/main.md docs/DESIGN.md docs/EVIDENCE.md docs/iterations.md docs/test_log.md docs/debugging_sessions.md docs/testing_and_evaluation.md -o all.docx; git add -u'
        language: system
        verbose: false
        always_run: true
    -   id: compile_all_pages
        name: Compile GitHub Pages
        entry: bash -c 'cat docs/main.md docs/DESIGN.md docs/EVIDENCE.md docs/iterations.md docs/test_log.md docs/debugging_sessions.md docs/testing_and_evaluation.md > docs/all.md; git add -u'
        language: system
        verbose: false
        always_run: true
    -   id: copy_readme
        name: Copy main to README
        entry: bash -c 'cp docs/main.md README.md; git add -u'
        language: system
        verbose: false
        always_run: true
